const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {spawnSync}=require('node:child_process');const crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'watch-deploy-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const project=path.join(dir,'project'),target=path.join(dir,'target');fs.mkdirSync(path.join(project,'desktop-patch'),{recursive:true});fs.mkdirSync(path.join(project,'desktop-patch/src'),{recursive:true});fs.mkdirSync(path.join(target,'src'),{recursive:true});const original='original source';fs.writeFileSync(path.join(target,'src/main.js'),original);fs.writeFileSync(path.join(project,'desktop-patch/src/main.js'),'patched source');fs.writeFileSync(path.join(project,'desktop-patch/base-manifest.json'),JSON.stringify({files:{'src/main.js':crypto.createHash('sha256').update(original).digest('hex')}}));return {dir,project,target,run:args=>spawnSync('python3',[path.join(root,'scripts/install-local-patch.py'),'--project',project,'--target',target,...args],{encoding:'utf8'})};}
test('installer previews without writing and refuses concurrent source changes',t=>{const f=setup(t);const before=fs.readFileSync(path.join(f.target,'src/main.js'),'utf8');assert.equal(f.run(['--check']).status,0);assert.equal(fs.readFileSync(path.join(f.target,'src/main.js'),'utf8'),before);fs.writeFileSync(path.join(f.target,'src/main.js'),'new live edit');assert.notEqual(f.run(['--apply','--backup',path.join(f.dir,'backup')]).status,0);assert.equal(fs.readFileSync(path.join(f.target,'src/main.js'),'utf8'),'new live edit');});
test('installer replaces only known source files and records recoverable originals',t=>{const f=setup(t);fs.writeFileSync(path.join(f.target,'state.sqlite'),'private data');fs.writeFileSync(path.join(f.target,'key.p8'),'private key');const backup=path.join(f.dir,'backup');const result=f.run(['--apply','--backup',backup]);assert.equal(result.status,0,result.stderr);assert.equal(fs.readFileSync(path.join(f.target,'src/main.js'),'utf8'),'patched source');assert.equal(fs.readFileSync(path.join(backup,'src/main.js'),'utf8'),'original source');assert.equal(fs.existsSync(path.join(backup,'key.p8')),false);assert.equal(fs.readFileSync(path.join(f.target,'state.sqlite'),'utf8'),'private data');});
test('installer preserves a live edit made after an earlier patch file was installed',t=>{
 const f=setup(t);const future=path.join(f.target,'src/prefs.js');
 fs.writeFileSync(future,'original source');fs.writeFileSync(path.join(f.project,'desktop-patch/src/prefs.js'),'new preferences');
 const manifest=path.join(f.project,'desktop-patch/base-manifest.json');const data=JSON.parse(fs.readFileSync(manifest));data.files['src/prefs.js']=data.files['src/main.js'];fs.writeFileSync(manifest,JSON.stringify(data));
 const program=`import importlib.util, argparse\nfrom pathlib import Path\nspec=importlib.util.spec_from_file_location('installer',${JSON.stringify(path.join(root,'scripts/install-local-patch.py'))})\nm=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)\noriginal_replace=m.os.replace\ndef replace(a,b):\n original_replace(a,b)\n if str(b).endswith('/src/main.js'): Path(${JSON.stringify(future)}).write_text('concurrent live edit')\nm.os.replace=replace\nm.run(argparse.Namespace(project=${JSON.stringify(f.project)},target=${JSON.stringify(f.target)},apply=True,backup=${JSON.stringify(path.join(f.dir,'backup'))}))\n`;
 const result=spawnSync('python3',['-c',program],{encoding:'utf8'});
 assert.notEqual(result.status,0,'concurrent live edit must stop the remaining patch');assert.equal(fs.readFileSync(future,'utf8'),'concurrent live edit');
});
test('Funnel preview is readonly and apply changes exactly one loopback mount',t=>{const f=setup(t);const cli=path.join(f.dir,'tailscale');const log=path.join(f.dir,'argv');fs.writeFileSync(cli,`#!/usr/bin/env python3\nimport sys,json\nfrom pathlib import Path\np=Path(${JSON.stringify(log)})\na=sys.argv[1:]\nif a[:3]==['funnel','status','--json']: print(json.dumps({'Web':{'host:443':{'Handlers':{'/api/watch-cellular/v1':{'Proxy':'http://127.0.0.1:8081/api/watch-cellular/v1'}}}}}))\nelse: p.write_text(json.dumps(a))\n`);fs.chmodSync(cli,0o755);const run=args=>spawnSync('bash',[path.join(root,'scripts/configure-clawd-watch-funnel.sh'),...args],{encoding:'utf8',env:{...process.env,CLAWD_TAILSCALE_BIN:cli}});assert.equal(run(['--port','23940']).status,0);assert.equal(fs.existsSync(log),false);const applied=run(['--apply','--port','23940']);assert.equal(applied.status,0,applied.stderr);assert.deepEqual(JSON.parse(fs.readFileSync(log,'utf8')),['funnel','--bg','--yes','--https=443','--set-path=/api/clawd-watch/v1','http://127.0.0.1:23940/api/clawd-watch/v1']);assert.notEqual(run(['--apply','--port','23333']).status,0);});
