const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {createWatchStore}=require('../src/watch-approval-store');const {createApprovalQueue}=require('../src/watch-approval-queue');const {createApprovalService}=require('../src/watch-approval-service');
function setup(t){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'watch-service-test-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const store=createWatchStore({directory});const device=store.pair(store.beginPairing().code);const entry={agentId:'codex',isCodex:true,res:{},createdAt:Date.now(),toolName:'Bash',toolInput:{command:'pwd'}};const queue=createApprovalQueue({getPendingPermissions:()=>[entry]});const [c]=queue.snapshot();return {store,device,entry,queue,input:{operationId:'12345678-1234-4234-8234-123456789abc',requestId:c.id,revision:c.revision,decision:'allow'}};}
test('concurrent retry of stable operation delivers once; changed decision conflicts',async t=>{const f=setup(t);let calls=0;const service=createApprovalService({...f,deliver:async()=>{calls++;return {status:'delivered'};}});const results=await Promise.all([service.submit(f.device,f.input),service.submit(f.device,f.input)]);assert.equal(calls,1);assert.equal(results[0].status,'delivered');assert.equal(f.store.getOperation(f.device.id,f.input.operationId).status,'delivered');await assert.rejects(service.submit(f.device,{...f.input,decision:'deny'}),e=>e.httpStatus===409);});
test('failed durable write never claims the queue or sends a decision',async t=>{const f=setup(t);fs.symlinkSync('/dev/null',path.join(path.dirname(path.join(f.store.directory,'watch-approval.json')),'bad'));fs.unlinkSync(path.join(f.store.directory,'watch-approval.json'));fs.symlinkSync('/dev/null',path.join(f.store.directory,'watch-approval.json'));let calls=0;const s=createApprovalService({...f,deliver:async()=>{calls++;}});await assert.rejects(s.submit(f.device,f.input));assert.equal(calls,0);assert.equal(f.queue.validate(f.input).entry,f.entry);});
test('restarted unknown receipt is queried without replaying approval',async t=>{const f=setup(t);f.store.recordClaim(f.device.id,f.input);const store=createWatchStore({directory:f.store.directory});let calls=0;const service=createApprovalService({...f,store,deliver:async()=>{calls++;}});assert.equal((await service.submit(f.device,f.input)).status,'unknown');assert.equal(calls,0);});
test('re-pairing the same push subscription removes the old device subscription durably',t=>{
 const f=setup(t);const next=f.store.pair(f.store.beginPairing().code);const push={token:'AB'.repeat(32),environment:'sandbox'};
 f.store.registerPush(f.device.id,push);f.store.registerPush(next.id,push);
 const restored=createWatchStore({directory:f.store.directory});const subscriptions=restored.listDevices().filter(d=>d.push);
 assert.equal(subscriptions.length,1);assert.equal(subscriptions[0].id,next.id);assert.equal(subscriptions[0].push.token,push.token.toLowerCase());
});
