const {test}=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {EventEmitter}=require('node:events');
const {createWatchPushSender}=require('../src/watch-approval-apns');
function setup(t,statuses=[200]){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'watch-apns-test-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const {privateKey,publicKey}=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'});const privateKeyPath=path.join(directory,'key.p8');fs.writeFileSync(privateKeyPath,privateKey.export({type:'pkcs8',format:'pem'}));let time=1000;const devices=[{id:'device',push:{token:'a'.repeat(64),environment:'sandbox'}}];const card={id:'12345678-1234-4234-8234-123456789abc',revision:'rev',agentId:'codex',toolName:'Bash',details:'secret command /home/user',canDecide:true,expiresAtMs:301000};const calls=[];const store={listDevices:()=>devices,registerPush:(id,p)=>{devices[0].push=p;}};
 const http2Connect=host=>{const client=new EventEmitter();client.close=()=>{};client.destroy=()=>{};client.request=headers=>{const stream=new EventEmitter();stream.setEncoding=()=>{};stream.close=()=>{};stream.setTimeout=()=>{};stream.end=body=>{calls.push({host,headers,payload:JSON.parse(body)});setImmediate(()=>{stream.emit('response',{':status':statuses.shift()??200});stream.emit('data',JSON.stringify({reason:'Unregistered'}));stream.emit('end');});};return stream;};return client;};
 const sender=createWatchPushSender({store,queue:{snapshot:()=>[card]},keyConfig:{teamId:'TEAM',keyId:'KEY',privateKeyPath,topic:'org.example.clawdwatch.watchapp'},http2Connect,now:()=>time});return {sender,calls,publicKey,devices,card,time:v=>time=v};}
test('signed push routes by environment and excludes command, paths and credentials',async t=>{const f=setup(t);await f.sender.scan();await f.sender.scan();assert.equal(f.calls.length,1);const c=f.calls[0];assert.equal(c.host,'https://api.sandbox.push.apple.com');assert.equal(c.headers['apns-topic'],'org.example.clawdwatch.watchapp');assert.equal(c.headers['apns-collapse-id'],f.card.id);assert.equal(Number(c.headers['apns-expiration']),301);assert.equal(JSON.stringify(c.payload).includes('secret command'),false);const jwt=c.headers.authorization.slice(7);const [head,body,sig]=jwt.split('.');assert.equal(JSON.parse(Buffer.from(head,'base64url')).alg,'ES256');assert.equal(crypto.verify('sha256',Buffer.from(head+'.'+body),{key:f.publicKey,dsaEncoding:'ieee-p1363'},Buffer.from(sig,'base64url')),true);f.devices[0].push={token:'b'.repeat(64),environment:'production'};await f.sender.scan();assert.equal(f.calls[1].host,'https://api.push.apple.com');});
test('invalid token is disabled and 503 retries are bounded by expiry',async t=>{const f=setup(t,[410]);await f.sender.scan();assert.equal(f.devices[0].push,null);const g=setup(t,[503,503,503,503,200]);await g.sender.scan();await g.sender.scan();assert.equal(g.calls.length,1);g.time(6000);await g.sender.scan();assert.equal(g.calls.length,2);g.time(36000);await g.sender.scan();assert.equal(g.calls.length,3);g.time(156000);await g.sender.scan();g.time(200000);await g.sender.scan();assert.equal(g.calls.length,4);});
test('expired or unapprovable card never generates push',async t=>{const f=setup(t,[503]);await f.sender.scan();f.time(302000);await f.sender.scan();assert.equal(f.calls.length,1);f.card.canDecide=false;f.card.expiresAtMs=500000;await f.sender.scan();assert.equal(f.calls.length,1);});
test('temporary suppression and a repaired device with the same token never repeat a successful push',async t=>{
 const f=setup(t);await f.sender.scan();f.card.canDecide=false;await f.sender.scan();f.card.canDecide=true;await f.sender.scan();
 assert.equal(f.calls.length,1,'DND recovery must retain delivery deduplication');
 f.devices.push({id:'repaired-device',push:{...f.devices[0].push}});await f.sender.scan();assert.equal(f.calls.length,1,'same physical subscription must not receive duplicate reminders');
});
