const {test}=require('node:test');const assert=require('node:assert/strict');const http=require('node:http');const {EventEmitter}=require('node:events');const Module=require('node:module');
const {createApprovalDelivery}=require('../src/watch-approval-delivery');
function factory(){const old=Module._load;Module._load=function(name){if(name==='electron')return {BrowserWindow:Object.assign(class{},{fromWebContents:()=>null}),globalShortcut:{register:()=>true,unregister(){},isRegistered:()=>false}};return old.apply(this,arguments);};let init;try{delete require.cache[require.resolve('../src/permission')];init=require('../src/permission');}finally{Module._load=old;}return init({sessions:new Map(),hideBubbles:false,petHidden:true,win:null,lang:'en',getBubblePolicy:()=>({enabled:true,autoCloseMs:null}),focusTerminalForSession(){},permDebugLog:null});}
function hook(api,agent){const res=new EventEmitter();let body;res.writeHead=()=>{};res.end=x=>{body=JSON.parse(x);res.writableEnded=true;res.writableFinished=true;res.emit('finish');};const entry={res,agentId:agent,isCodex:agent==='codex',isKimi:agent==='kimi-cli',sessionId:'s',createdAt:Date.now(),toolName:'Bash',toolInput:{command:'pwd'},resolvedSuggestion:{type:'addRules',behavior:'allow'}};api.pendingPermissions.push(entry);return {entry,res,body:()=>body};}
for(const agent of ['codex','kimi-cli','claude-code']) test(`${agent} reports original one-time hook decision`,async()=>{const api=factory();const f=hook(api,agent);const deliver=createApprovalDelivery({resolvePermissionEntry:api.resolvePermissionEntry,getPendingPermissions:()=>api.pendingPermissions});assert.equal((await deliver(f.entry,'allow')).status,'delivered');const output=f.body().hookSpecificOutput;assert.equal(JSON.stringify(output).includes('updatedPermissions'),false);assert.equal(JSON.stringify(output).includes('allow'),true);assert.equal(api.pendingPermissions.length,0);assert.equal((await deliver(f.entry,'deny')).status,'handledElsewhere');});
test('ended socket and write failure cannot be success',async()=>{const api=factory();const f=hook(api,'codex');f.res.destroyed=true;const deliver=createApprovalDelivery({resolvePermissionEntry:api.resolvePermissionEntry,getPendingPermissions:()=>api.pendingPermissions});assert.equal((await deliver(f.entry,'allow')).status,'handledElsewhere');f.res.destroyed=false;f.res.writeHead=()=>{throw Error('write failed');};assert.equal((await deliver(f.entry,'allow')).status,'unknown');});
for(const [reply,status] of [[{accepted:true},'delivered'],[{accepted:false,reason:'not-pending'},'handledElsewhere'],[{},'unknown']])test(`DSH confirms ${status} from real HTTP reply`,async t=>{const api=factory();let payload;const server=http.createServer((req,res)=>{let data='';req.on('data',d=>data+=d);req.on('end',()=>{payload=JSON.parse(data);res.setHeader('content-type','application/json');res.end(JSON.stringify(reply));});});await new Promise((r,j)=>{server.once('error',j);server.listen(0,'127.0.0.1',r);});t.after(()=>server.close());const entry={agentId:'deepseek-harness',isDeepseek:true,sessionId:'dsh:s',toolName:'bash',toolInput:{command:'pwd'},deepseek:{port:server.address().port,rpcId:'rpc',approvalId:'approval'}};api.pendingPermissions.push(entry);const deliver=createApprovalDelivery({resolvePermissionEntry:api.resolvePermissionEntry,getPendingPermissions:()=>api.pendingPermissions});assert.equal((await deliver(entry,'allow')).status,status);assert.equal(payload.result.value.outcome,'allowed-once');assert.equal(payload.result.value.sessionId,'s');});
test('DSH transport errors resolve unknown without unhandled rejection',async()=>{const api=factory();assert.equal((await api.replyDeepseekApproval({port:1,rpcId:'r',sessionId:'s',approvalId:'a',outcome:'rejected'})).status,'unknown');});
test('hook delivery waits for actual stream finish and reports asynchronous failure',async()=>{
 const api=factory();const f=hook(api,'codex');f.res.end=()=>{};
 const deliver=createApprovalDelivery({resolvePermissionEntry:api.resolvePermissionEntry,getPendingPermissions:()=>api.pendingPermissions});
 let settled=false;const result=deliver(f.entry,'allow').then(r=>{settled=true;return r;});
 await new Promise(r=>setImmediate(r));assert.equal(settled,false);
 f.res.emit('error',Error('socket write failed'));assert.equal((await result).status,'unknown');
});
